[source]
title = "Information Geometry"
year = 2017
uri = "https://doi.org/10.1007/978-3-319-56478-4"
file = "Information Geometry.pdf"

[[author]]
first_name = "Nihat"
last_name = "Ay"

[[author]]
first_name = "Jürgen"
last_name = "Jost"

[[author]]
first_name = "Hông Vân"
last_name = "Lê"

[[author]]
first_name = "Lorenz"
last_name = "Schwachhöfer"

